version: '3'

services:
  acapymultytenant:
    image: vskgr/aca-py
    container_name: mtacapy
    hostname: mtacapy
    ports:
      - "${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}"
      - "${ACAPY_ENDPOINT_PORT}:${ACAPY_ENDPOINT_PORT}"
    environment:
      WAIT_HOSTS: "dbmt:4444"
      WAIT_HOSTS_TIMEOUT: "300"
      WAIT_SLEEP_INTERVAL: "5"
      WAIT_HOST_CONNECT_TIMEOUT: "3"
      ACAPY_ENDPOINT: "${ACAPY_ENDPOINT}"
      ACAPY_GENESIS_URL: "${LEDGER_URL}/genesis"
      ACAPY_INBOUND_TRANSPORT: "[[\"http\", \"0.0.0.0\", \"9990\"]]"
      ACAPY_OUTBOUND_TRANSPORT: http
      LEDGER_URL: "${LEDGER_URL}"
      ACAPY_TAILS_SERVER_BASE_URL: "${TAILS_SERVER_URL}"
      ACAPY_TRACE_TARGET: log
      ACAPY_TRACE_TAG: acapy.event
      ACAPY_WEBHOOK_URL: "${WEB_HOOK_URL}"
      ACAPY_WALLET_TYPE: "indy"
      ACAPY_WALLET_KEY: "${ACAPY_WALLET_KEY}"
      ACAPY_WALLET_NAME: "multytenant"
      ACAPY_WALLET_STORAGE_TYPE: "postgres_storage"
      ACAPY_WALLET_STORAGE_CONFIG: '{"url":"dbmt:4444","max_connections":5}'
      ACAPY_WALLET_STORAGE_CREDS: '{"account": "postgres","password":"password","admin_account":"postgres","admin_password":"password"}'
      ACAPY_WALLET_SEED: "${ACAPY_WALLET_SEED_ONE}"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PING_CONNECTION: "true"
      ACAPY_RECREATE_WALLET: "true"
      ACAPY_MULTITENANT: "true"
      ACAPY_MULTITENANT_JWT_SECRET: "${ACAPY_MULTITENANT_JWT_SECRET}"
      ACAPY_MULTITENANT_ADMIN: "true"
      ACAPY_LABEL: "${ACAPY_LABEL}"
      ACAPY_LOG_LEVEL: "${ACAPY_LOG_LEVEL}"
    command: "start --admin 0.0.0.0 ${ACAPY_ADMIN_PORT}"

  dbmt:
    image: postgres:latest
    hostname: dbmt
    container_name: dbmt
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ./.postgres:/var/lib/postgresql
    ports:
      - "4444:4444"
    command: -p 4444
  tails-server-mt:
    image: vskgr/tails-server
    ports:
      - 6544:6544
    volumes:
      - /issuer/tails-files:/tails-files/
    environment:
      GENESIS_URL: "${LEDGER_URL}/genesis"
      TAILS_SERVER_URL: "${TAILS_SERVER_URL}"
    command: >
      tails-server
        --host 0.0.0.0
        --port 6544
        --storage-path /tails-files
        --log-level INFO
  # pgAdmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
